### ISSUE TITLE
`flickr_api.auth.AuthHandler()` excepts with http error 401 

### ISSUE THREAD

**Issue by eric-saintetienne** [alexis-mignon/python-flickr-api#139]
The backtraces says it all:

```python
Python 3.12.6 (main, Sep  9 2024, 00:00:00) [GCC 14.2.1 20240801 (Red Hat 14.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import flickr_api
>>> API_KEY = '...'  # redacted
>>> API_SECRET = '...'  # redacted
>>> flickr_api.set_keys(api_key=API_KEY, api_secret=API_SECRET)
>>> a = flickr_api.auth.AuthHandler()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eric/git/flickr_download/venv/lib64/python3.12/site-packages/flickr_api/auth.py", line 87, in __init__
    resp = urlopen_and_read(req.to_url())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eric/git/flickr_download/venv/lib64/python3.12/site-packages/flickr_api/utils.py", line 11, in urlopen_and_read
    x = urllib.request.urlopen(url)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

The packages installed (in a virtual environment):
```
pip freeze
attrs==24.2.0
certifi==2024.8.30
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
Cython==3.0.11
flickr-api==0.7.7
flickr-download==0.3.6
httplib2==0.22.0
idna==3.10
interrogate==1.7.0
oauth2==1.9.0.post1
pathvalidate==2.5.2
py==1.11.0
pyparsing==3.1.4
python-dateutil==2.9.0.post0
pyutil==3.3.6
PyYAML==5.3
requests==2.32.3
six==1.16.0
tabulate==0.9.0
urllib3==2.2.3
```
Thanks for looking at this problem.

**Comment by beaufour** [comment]
Are you sure your API credentials are valid given that 401 is unauthorized?
