### ISSUE TITLE
Getting: flickr_api.flickrerrors.FlickrAPIError: 5 : Filetype was not recognised

### ISSUE THREAD

**Issue by JoabMendes** [alexis-mignon/python-flickr-api#64]
I ran this code to upload a picture (The authentication is working):
```python
f_photo = flickr_api.upload(photo_file = os.path.abspath("florian.gif"), title = "My title")
```

But I am getting the error

```shell
Traceback (most recent call last):
  File "import_second.py", line 42, in <module>
    f_photo = flickr_api.upload(photo_file = os.path.abspath("florian.gif"), title = "My title")
  File "/Users/joabe/Library/Python/2.7/lib/python/site-packages/flickr_api-0.5-py2.7.egg/flickr_api/upload.py", line 103, in upload
    r = post(UPLOAD_URL, auth.AUTH_HANDLER, args, photo_file, photo_file_data)
  File "/Users/joabe/Library/Python/2.7/lib/python/site-packages/flickr_api-0.5-py2.7.egg/flickr_api/upload.py", line 62, in post
    raise FlickrAPIError(int(err.get("code")), err.get("msg"))
flickr_api.flickrerrors.FlickrAPIError: 5 : Filetype was not recognised
```
Is it the way I am sending the photo_file path? 
Is there as specific way to call to use the upload function?

**Comment by JoabMendes** [comment]
The problema was that I tried to upload a gif. lol
