### ISSUE TITLE
Exception UnboundLocalError if server response not 200 when uploading photo

### ISSUE THREAD

**Issue by wladich** [alexis-mignon/python-flickr-api#95]
```
Traceback (most recent call last):
 
  File "/home/w/projects/panoedit/flickr_upload.py", line 60, in main
    path = os.path.join(conf.photos_dir, file_name)
  File "/home/w/projects/panoedit/google_venv/local/lib/python2.7/site-packages/flickr_api/upload.py", line 107, in upload
    r = post(UPLOAD_URL, auth.AUTH_HANDLER, args, photo_file, photo_file_data)
  File "/home/w/projects/panoedit/google_venv/local/lib/python2.7/site-packages/flickr_api/upload.py", line 61, in post
    raise FlickrError("HTTP Error %i: %s" % (r.status, data))
UnboundLocalError: local variable 'r' referenced before assignment
```

**Comment by wladich** [comment]
Line 61 in upload.py should be 
```
raise FlickrError("HTTP Error %i: %s" % (resp.status_code, data))
```
Also note that it should be resp.status _code, not resp.status.
